### PR TITLE
latte3 compatibility

### PR DESCRIPTION
**Pull request by jkavalik**
I updated the wizard to Latte v3
- implemented Latte extension
- DI extension registers macros/tags depending on Latte version
- tests were updated and will fail with Latte v2
- changed the compatibility matrix for CI - minimal set to 7.4 (older versions are significantly EOL) and allowed tests up to 8.2

The tests pass and it works for me, but I did not do any extensive testing yet.

### CODE REVIEW

**Comment by jkavalik** [comment]
Should I only allow php8+ tests or make the tests switch paths depending on versions?

**Comment by f3l1x** [comment]
Hi @jkavalik. Yep, allow only PHP 8.0+. Also in composer.json.

**Comment by Kocicak** [comment]
Hi @f3l1x, can this PR be approved, or are you waiting for some more work to be done? Thanks

**Comment by f3l1x** [comment]
Hi @Kocicak @jkavalik merged. Thank you for your work here.

**Pull request merged**
